package main

const outputTemplate = `// this file is generated by github.com/f1shl3gs/bindata
// do not edit it manually
// 
// Timestamp:   {{ .timestamp.Format "2006-01-02T15:04:05Z07:00" }}
// Gzip Level:  {{ .gzip }}
//
// Input Files:
{{ range $key, $value := .entries -}}
//   {{ $key }}
{{- end }}

{{ .tags }}

package {{ .package }}

{{ .misc -}}

var files = map[string]file{
    {{- range $key, $value := .entries }}
    {{ $stat := stat $value -}}
    "{{ $key }}": {
		data: []byte("{{ string $value }}"),
		FileInfo: &fileInfo{
			name:    "{{ $key }}",
			size:    {{ $stat.Size }},
			modTime: time.Unix({{ $stat.ModTime.Unix }}, 0),
		},
	},
    {{ end }}
}
`
